### ISSUE TITLE
Some problems about DGL version

### ISSUE THREAD

**Issue by XiXiphus** [langgege-cqu/maxp_dgl#1]
I noticed that in file dgl_env.yaml there shows DGL version is dgl-cu113==0.8a211214 but actually I can only pip install or conda install dgl-cu113==0.8.0. But when I have successfully installed dgl-cu113==0.8.0 there was an error about "from dgl.dataloading.neighbor import MultiLayerNeighborSampler". From DGL official document, it shows that  MultiLayerNeighborSampler function exists in early version dgl-cu102==0.6.0, but when I switched to that, another error about "missing function dglnn.GATv2Conv" happened.

I guessed that dgl-cu113==0.8a211214 was a very special version DGL only made for maxp competition, so how can I get the correct version of DGL?

**Comment by zlaom** [comment]
![image](https://user-images.githubusercontent.com/16085476/185074864-164e1ca3-38ce-4a0b-95d9-fb7e88b0efdf.png)
In the version 0.9.0 the source code file path was changed, you must change it from `from dgl.dataloading` to `from dgl._dataloading`

for example

```python
import dgl
from dgl._dataloading.neighbor import MultiLayerNeighborSampler
from dgl._dataloading.pytorch import NodeDataLoader
````
